### ISSUE TITLE
Some bugs when reproducing the results of the paper:biological network growth. 

### ISSUE THREAD

**Issue by HuKangxin** [CIA-CCTB/pythrahyper_net#13]
I met a problem when I rerun the Multicellular-Network.ipynb. We know that the  variable 'forcep' is the input of 'init_par_growing', and this variable is needed at 'external_forces' function. But the question is when I run '# Starting the growth process simulation'  part in Multicellular-Network.ipynb. The result is shown as 'name 'forcep' is not defined'. I think the reason might be that 'forcep' is imported in 'init_par_growing' function, while this function contains lots of another function that need the variable 'forcep'. It seems like my Python cannot recognize that 'forcep' is already imported in the root function. I don't how to address this problem. If any of professional programmers knows how to solve it, I will thank him or her very much.

**Comment by TorstenPaul** [comment]
Dear HuKangxin you are welcome. We will address this issue as soon as possible.

Do not hesitate to ask further questions concering the scripts.

Greetings Torsten

@HuKangxin 
@phi-max 
@TorstenPaul

**Comment by HuKangxin** [comment]
WoW! Thanks for your reply very much. This is the URL of detailed image information of the Error. Hope this can help you.
https://i.bmp.ovh/imgs/2021/10/f972368acde590ad.png
There maybe other reasons that I use Python 3.8 instead of Python 3.7. Moreover, I am still very confused of a sentence in the 'readme.md' which is 'start a Jupyter notebook server in the `pythrahyper_net` directory to access the notebooks'. What I do is just open jupyter in the 'pythrahyper_net' directory in my computer. Just like this https://i.bmp.ovh/imgs/2021/10/3a6247d72165f27d.png
Maybe there are some problems here.

**Comment by HuKangxin** [comment]
> Dear HuKangxin you are welcome. We will address this issue as soon as possible.
> 
> Do not hesitate to ask further questions concering the scripts.
> 
> Greetings Torsten
> 
> @HuKangxin @phi-max @TorstenPaul

WoW! Thanks for your reply very much. This is the URL of detailed image information of the Error. Hope this can help you.
https://i.bmp.ovh/imgs/2021/10/f972368acde590ad.png
There maybe other reasons that I use Python 3.8 instead of Python 3.7. Moreover, I am still very confused of a sentence in the 'readme.md' which is 'start a Jupyter notebook server in the pythrahyper_net directory to access the notebooks'. What I do is just open jupyter in the 'pythrahyper_net' directory in my computer. Just like this https://i.bmp.ovh/imgs/2021/10/3a6247d72165f27d.png
Maybe there are some problems here.
@TorstenPaul

**Comment by HuKangxin** [comment]
The problem has been solved. I tried to run "initialize_Network_Growing" firstly, then I found out there is no question for the code. So I chose to replace the .ipynb with the new one and run it again, success.
